name: workplace
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - jupyterlab>=3
  - nodejs
  - nbresuse
  - psutil
  - r-irkernel
  - r-base>=4
  - r-tidyverse
  - pip:
    - postgres_kernel
